### ISSUE TITLE
controllerService没有正确导入命名空间

### ISSUE THREAD

**Issue by Delta1035** [sharebravery/openapi-genuu#2]
![253852600e53b41dd867cac34b61777e](https://github.com/sharebravery/openapi-genuu/assets/51444562/863416ff-dff8-461f-9052-e2c86f9bd328)

**Comment by Delta1035** [comment]
![image](https://github.com/sharebravery/openapi-genuu/assets/51444562/bd360b30-edb2-4270-8cbc-21d39e748fa4)
models被写死了

**Comment by sharebravery** [comment]
请提供一份可复现生成效果的API JSON文件

**Comment by sharebravery** [comment]
已经进行了修复
